### ISSUE TITLE
Screenshots do not match the app

### ISSUE THREAD

**Issue by natdebru** [david-knigge/NAS19-Friendsr#1]
I want to watch this app but the screenshot do not look like the app

**Comment by natdebru** [comment]
Are you gonna fix this or...?

**Comment by david-knigge** [comment]
damn thanks for catching this major bug would have definitely gotten in trouble in production thanks so much omg

**Comment by natdebru** [comment]
I understand but this is a very important issue which should be fixed

**Comment by david-knigge** [comment]
stop commenting on this closed thread please

**Comment by david-knigge** [comment]
oh sorry
